#!/usr/bin/env python3
"""
zephyr-mojo code generator.

Reads the Zephyr API specification (spec.py) and generates Mojo source files
for the raw bindings layer (zephyr_sys).

All generated functions use `raises` because Python ctypes calls can raise.
"""

import os
from datetime import datetime
from codegen.spec import FUNCTIONS, ERRNO_MAP

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def generate_zephyr_sys(output_dir: str = None) -> str:
    if output_dir is None:
        output_dir = os.path.join(PROJECT_ROOT, "zephyr_sys")
    os.makedirs(output_dir, exist_ok=True)

    lines = []
    _emit_header(lines)
    _emit_ffi_backend(lines)
    _emit_constants(lines)
    _emit_timeout_helpers(lines)
    _emit_error_codes(lines)
    _emit_functions(lines)

    output = "\n".join(lines) + "\n"
    output_path = os.path.join(output_dir, "__init__.mojo")
    with open(output_path, "w") as fh:
        fh.write(output)

    print(f"Generated {output_path} ({len(FUNCTIONS)} functions)")
    return output_path


def _emit_header(lines):
    lines.append("# === AUTO-GENERATED by codegen/gen_sys.py ===")
    lines.append(f"# Generated: {datetime.now().isoformat()}")
    lines.append("# Zephyr kernel API raw bindings (via Python ctypes FFI).")
    lines.append("# Do not edit by hand — run `python3 -m codegen.gen_sys`.")
    lines.append("")
    lines.append("from std.python import Python, PythonObject")
    lines.append("")


def _emit_ffi_backend(lines):
    lines.append("# ─── FFI Backend ───────────────────────────────────────────────")
    lines.append("# Lazy-initialized ctypes CDLL. Each function calls _get_lib().")
    lines.append("")
    lines.append("")
    lines.append("def _get_lib() raises -> PythonObject:")
    lines.append('    """Lazily load the C library for FFI calls."""')
    lines.append("    var ctypes = Python.import_module(\"ctypes\")")
    lines.append("    # CDLL(None) loads symbols from the current process (libc etc.)")
    lines.append("    return ctypes.CDLL(Python.evaluate(\"None\"))")
    lines.append("")


def _emit_constants(lines):
    lines.append("# ─── Zephyr Constants ──────────────────────────────────────────")
    lines.append("")
    lines.append("comptime K_NO_WAIT: Int64 = 0")
    lines.append("comptime K_FOREVER: Int64 = -1")
    lines.append("comptime K_SEM_MAX_LIMIT: UInt64 = 0xFFFFFFFF")
    lines.append("comptime K_POLL_TYPE_SEM_AVAILABLE: UInt32 = 0")
    lines.append("comptime K_POLL_TYPE_DATA_AVAILABLE: UInt32 = 1")
    lines.append("comptime K_POLL_TYPE_SIGNAL: UInt32 = 3")
    lines.append("")


def _emit_timeout_helpers(lines):
    lines.append("# ─── Timeout helpers ───────────────────────────────────────────")
    lines.append("")
    lines.append("")
    lines.append("def timeout_no_wait() -> Int64:")
    lines.append('    """K_NO_WAIT — return immediately without blocking."""')
    lines.append("    return K_NO_WAIT")
    lines.append("")
    lines.append("")
    lines.append("def timeout_forever() -> Int64:")
    lines.append('    """K_FOREVER — wait indefinitely."""')
    lines.append("    return K_FOREVER")
    lines.append("")
    lines.append("")
    lines.append("def timeout_ms(ms: Int) -> Int64:")
    lines.append('    """Convert milliseconds to a k_timeout_t ticks value."""')
    lines.append("    return Int64(ms)")
    lines.append("")


def _emit_error_codes(lines):
    lines.append("# ─── Zephyr error codes (negated errno as positive u32) ───────")
    lines.append("")
    for code, name in sorted(ERRNO_MAP.items()):
        if code == 0:
            continue
        lines.append(f"comptime E{name}: UInt32 = {code}")
    lines.append("")
    lines.append("")
    lines.append("def errno_name(code: UInt32) -> String:")
    lines.append('    """Return the errno name for a Zephyr error code."""')
    first = True
    for code, name in sorted(ERRNO_MAP.items()):
        if code == 0:
            continue
        kw = "if" if first else "elif"
        first = False
        lines.append(f"    {kw} code == {code}:")
        lines.append(f'        return "{name}"')
    lines.append('    return "UNKNOWN"')
    lines.append("")


def _emit_functions(lines):
    lines.append("# ─── Kernel API Functions ──────────────────────────────────────")
    lines.append("# All functions use `raises` (Python ctypes calls may raise).")
    lines.append("")

    categories = {}
    for f in FUNCTIONS:
        cat = f.category
        categories.setdefault(cat, []).append(f)

    for cat_name in categories:
        lines.append(f"# ── {cat_name.upper()} ─{'─' * (60 - len(cat_name))}")
        lines.append("")
        for func in categories[cat_name]:
            _emit_function(lines, func)


def _emit_function(lines, func):
    """Emit a single Zephyr function wrapper."""

    # Build parameter list (pointers → Int)
    params = []
    for p in func.params:
        if p.is_pointer:
            params.append(f"{p.name}: Int")
        else:
            params.append(f"{p.name}: {p.mojo_type}")
    param_str = ", ".join(params)

    # Return type
    if func.mojo_return in ("NoneType",):
        ret = ""
    elif func.mojo_return == "Pointer":
        ret = " -> Int"
    else:
        ret = f" -> {func.mojo_return}"

    # Function signature with raises
    lines.append(f"def {func.name}({param_str}) raises{ret}:")

    # Docstring INSIDE function body
    lines.append(f'    """{func.description}"""')

    # Body
    lines.append("    var lib = _get_lib()")

    # Build ctypes call arguments
    args_parts = []
    for p in func.params:
        if p.mojo_type in ("Int64", "Int"):
            args_parts.append(f"PythonObject({p.name})")
        elif p.mojo_type == "UInt32":
            args_parts.append(f"PythonObject(Int({p.name}))")
        elif p.mojo_type == "UInt64":
            args_parts.append(f"PythonObject(Int({p.name}))")
        else:
            args_parts.append(f"PythonObject({p.name})")

    args_str = ", ".join(args_parts)

    # Return handling
    if func.mojo_return in ("NoneType",):
        lines.append(f"    var _ = lib.{func.name}({args_str})")
    else:
        lines.append(f"    var _py = lib.{func.name}({args_str})")
        if func.mojo_return == "Int":
            lines.append("    return Int(py=_py)")
        elif func.mojo_return == "Int64":
            lines.append("    return Int64(Int(py=_py))")
        elif func.mojo_return == "UInt32":
            lines.append("    return UInt32(Int(py=_py))")
        elif func.mojo_return == "UInt64":
            lines.append("    return UInt64(Int(py=_py))")
        elif func.mojo_return == "Pointer":
            lines.append("    return Int(py=_py)")
        else:
            lines.append(f"    return {func.mojo_return}(_py)")

    lines.append("")


if __name__ == "__main__":
    path = generate_zephyr_sys()
    print(f"Done. Output: {path}")
