#!/usr/bin/env python3
"""
zephyr-mojo code generator.

Reads the Zephyr API specification (spec.py) and generates Mojo source files
for the raw bindings layer (zephyr_sys).

Supports two backends:
  --backend ctypes  Python ctypes FFI (default, works on stable Mojo 1.0)
  --backend native  Native std.ffi.external_call (requires nightly Mojo)

Usage:
  python3 -m codegen.gen_sys                  # default (ctypes)
  python3 -m codegen.gen_sys --backend native  # native FFI
"""

import os
import sys
from datetime import datetime
from codegen.spec import FUNCTIONS, ERRNO_MAP
from codegen.backends import get_backend, is_void_type


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def generate_zephyr_sys(output_dir: str = None, backend_name: str = "ctypes") -> str:
    """Generate the zephyr_sys/__init__.mojo file."""
    if output_dir is None:
        output_dir = os.path.join(PROJECT_ROOT, "zephyr_sys")
    os.makedirs(output_dir, exist_ok=True)

    backend = get_backend(backend_name)

    lines = []
    _emit_header(lines, backend_name)
    _emit_imports(lines, backend)
    _emit_ffi_setup(lines, backend)
    _emit_constants(lines)
    _emit_timeout_helpers(lines)
    _emit_error_codes(lines)
    _emit_function_section(lines, backend)

    output = "\n".join(lines) + "\n"
    output_path = os.path.join(output_dir, "__init__.mojo")
    with open(output_path, "w") as fh:
        fh.write(output)

    print(f"Generated {output_path} ({len(FUNCTIONS)} functions, backend={backend_name})")
    return output_path


def _emit_header(lines, backend_name):
    lines.append("# === AUTO-GENERATED by codegen/gen_sys.py ===")
    lines.append(f"# Generated: {datetime.now().isoformat()}")
    lines.append(f"# Backend: {backend_name}")
    lines.append("# Zephyr kernel API raw bindings.")
    lines.append("# Do not edit by hand — run `python3 -m codegen.gen_sys`.")
    lines.append("")


def _emit_imports(lines, backend):
    for imp in backend.emit_imports():
        lines.append(imp)
    lines.append("")


def _emit_ffi_setup(lines, backend):
    setup = backend.emit_get_lib()
    if setup:
        lines.append("# ─── FFI Backend Setup ──────────────────────────────────────────")
        for line in setup:
            lines.append(line)
        lines.append("")


def _emit_constants(lines):
    lines.append("# ─── Zephyr Constants ──────────────────────────────────────────")
    lines.append("")
    lines.append("comptime K_NO_WAIT: Int64 = 0")
    lines.append("comptime K_FOREVER: Int64 = -1")
    lines.append("comptime K_SEM_MAX_LIMIT: UInt64 = 0xFFFFFFFF")
    lines.append("comptime K_POLL_TYPE_SEM_AVAILABLE: UInt32 = 0")
    lines.append("comptime K_POLL_TYPE_DATA_AVAILABLE: UInt32 = 1")
    lines.append("comptime K_POLL_TYPE_SIGNAL: UInt32 = 3")
    lines.append("")


def _emit_timeout_helpers(lines):
    lines.append("# ─── Timeout helpers ───────────────────────────────────────────")
    lines.append("")
    lines.append("")
    lines.append("def timeout_no_wait() -> Int64:")
    lines.append('    """K_NO_WAIT — return immediately without blocking."""')
    lines.append("    return K_NO_WAIT")
    lines.append("")
    lines.append("")
    lines.append("def timeout_forever() -> Int64:")
    lines.append('    """K_FOREVER — wait indefinitely."""')
    lines.append("    return K_FOREVER")
    lines.append("")
    lines.append("")
    lines.append("def timeout_ms(ms: Int) -> Int64:")
    lines.append('    """Convert milliseconds to a k_timeout_t ticks value."""')
    lines.append("    return Int64(ms)")
    lines.append("")


def _emit_error_codes(lines):
    lines.append("# ─── Zephyr error codes (negated errno as positive u32) ───────")
    lines.append("")
    for code, name in sorted(ERRNO_MAP.items()):
        if code == 0:
            continue
        lines.append(f"comptime E{name}: UInt32 = {code}")
    lines.append("")
    lines.append("")
    lines.append("def errno_name(code: UInt32) -> String:")
    lines.append('    """Return the errno name for a Zephyr error code."""')
    first = True
    for code, name in sorted(ERRNO_MAP.items()):
        if code == 0:
            continue
        kw = "if" if first else "elif"
        first = False
        lines.append(f"    {kw} code == {code}:")
        lines.append(f'        return "{name}"')
    lines.append('    return "UNKNOWN"')
    lines.append("")


def _emit_function_section(lines, backend):
    lines.append("# ─── Kernel API Functions ──────────────────────────────────────")
    if backend.name == "ctypes":
        lines.append("# Called through Python ctypes (Mojo -> Python -> C).")
    else:
        lines.append("# Called directly via std.ffi.external_call (zero-overhead C FFI).")
    lines.append("")

    categories = {}
    for f in FUNCTIONS:
        cat = f.category
        categories.setdefault(cat, []).append(f)

    line_count = 0
    for cat_name in categories:
        lines.append(f"# ── {cat_name.upper()} ─{'─' * (60 - len(cat_name))}")
        lines.append("")
        for func in categories[cat_name]:
            for line in backend.emit_function(func):
                lines.append(line)
                line_count += 1

    # Remove trailing blank lines
    while lines and lines[-1] == "":
        lines.pop()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate zephyr_sys Mojo bindings")
    parser.add_argument("--backend", choices=["ctypes", "native"], default="ctypes",
                        help="FFI backend (default: ctypes)")
    args = parser.parse_args()

    path = generate_zephyr_sys(backend_name=args.backend)
    print(f"Done. Output: {path}")
